
//! Autogenerated weights for `pallet_credit_accumulation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-11-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `yubo-X400`, CPU: `AMD Ryzen 7 PRO 4750G with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/debug/deeper-chain
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_credit_accumulation
// --no-storage-info
// --no-median-slopes
// --no-min-squares
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/credit-accumulation/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_credit_accumulation`.
pub trait WeightInfo {
	fn add_credit_by_traffic() -> Weight;
	fn set_atmos_pubkey() -> Weight;
}

/// Weights for `pallet_credit_accumulation` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `CreditAccumulation::AtmosNonce` (r:1 w:1)
	/// Proof: `CreditAccumulation::AtmosNonce` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CreditAccumulation::AtmosAccountid` (r:1 w:0)
	/// Proof: `CreditAccumulation::AtmosAccountid` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CreditAccumulation::TmpAtmosAccountid` (r:1 w:0)
	/// Proof: `CreditAccumulation::TmpAtmosAccountid` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `DeeperNode::OnboardTime` (r:1 w:0)
	/// Proof: `DeeperNode::OnboardTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_credit_by_traffic() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `378`
		//  Estimated: `3843`
		// Minimum execution time: 584_376_000 picoseconds.
		Weight::from_parts(596_257_000, 3843)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `CreditAccumulation::AtmosAccountid` (r:0 w:1)
	/// Proof: `CreditAccumulation::AtmosAccountid` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_atmos_pubkey() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 86_237_000 picoseconds.
		Weight::from_parts(90_966_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `CreditAccumulation::AtmosNonce` (r:1 w:1)
	/// Proof: `CreditAccumulation::AtmosNonce` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CreditAccumulation::AtmosAccountid` (r:1 w:0)
	/// Proof: `CreditAccumulation::AtmosAccountid` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CreditAccumulation::TmpAtmosAccountid` (r:1 w:0)
	/// Proof: `CreditAccumulation::TmpAtmosAccountid` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `DeeperNode::OnboardTime` (r:1 w:0)
	/// Proof: `DeeperNode::OnboardTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_credit_by_traffic() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `378`
		//  Estimated: `3843`
		// Minimum execution time: 584_376_000 picoseconds.
		Weight::from_parts(596_257_000, 3843)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `CreditAccumulation::AtmosAccountid` (r:0 w:1)
	/// Proof: `CreditAccumulation::AtmosAccountid` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_atmos_pubkey() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 86_237_000 picoseconds.
		Weight::from_parts(90_966_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
