[package]
name = "fp-storage"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io"]
edition = "2018"
description = "Storage primitives for Ethereum RPC (web3) compatibility layer for Substrate."
license = "Apache-2.0"

[features]
default = ["std"]
std = []
